### ISSUE TITLE
Pretrain implementation issue

### ISSUE THREAD

**Issue by moonboy12138** [antofuller/CROMA#6]
I apologize for reaching out again. Upon reviewing your pretraining code release, it appears that the decoder requires the addition of alibi positional embedding; otherwise, coding errors may occur. Alternatively, should I attempt to include a new attention block for the decoder without alibi?

Additionally, I'm curious about the choice of using 2D sinusoidal for the decoder instead of continuing with alibi.

**Comment by antofuller** [comment]
Hi, I'm very sorry for the 2-week delay.

In preliminary experiments training vanilla MAE on SSL4EO, I found 2D-ALiBi outperformed 2D-sincos only in the encoder—2D-ALiBi in the decoder didn't perform well. So, when developing CROMA, I didn't even try to use 2D-ALiBi in the decoder.

I'm not sure I understand your first question. DecoderMAE should not use 2D-ALiBi. Can you please clarify your concern?

**Comment by moonboy12138** [comment]
Thanks for your reply! My first question is in DecoderMAE, you use the Basetransformer block as decoder, but the Basetransformer block needs a input of alibi, so should I just remove the input of alibi? 
BTW, I wonder if you use the same dataloader file in [here](https://github.com/zhu-xlab/SSL4EO-S12/tree/main/src/benchmark/pretrain_ssl/datasets/SSL4EO), I'll be appreciate if you release the dataset load and process codes.

**Comment by antofuller** [comment]
BaseTransformer now defaults alibi to None so it should be able to handle the case when alibi is not passed to it (i.e., in DecoderMAE).

I followed SatMAE's data preprocessing and used my own dataloader, which was specific to the hardware I used to pretrain all models.

**Comment by moonboy12138** [comment]
Thank you for your patient response!

**Comment by moonboy12138** [comment]
Thank you for your patient response!
